### ISSUE TITLE
[CE-102] Improved REST API Validation Message on Duplicate Option

### ISSUE THREAD

**Issue by jahdroid** [codeclou/customfield-editor-for-jira#102]
### Story

Return optionid of duplicate option in validation error message

### Acceptance Criteria

 * ✅  optionid of duplicate option in validation error message in REST API Calls for creating and editing options and childoptions
 * :red_circle: inform CEPS-48 once done

----

### :zap: REST API Changes

Affected Endpoints

 * `POST /user/customfields/{customFieldId}/contexts/default/options`
 * `PUT  /user/customfields/{customFieldId}/contexts/default/options/{optionId}`
 * `POST /user/customfields/{customFieldId}/contexts/{contextId}/options`
 * `PUT  /user/customfields/{customFieldId}/contexts/{contextId}/options/{optionId}`
 * `POST /user/customfields/{customFieldId}/contexts/default/options/{optionId}/childoptions`
 * `PUT  /user/customfields/{customFieldId}/contexts/default/options/{optionId}/childoptions/{childOptionId}`
 * `POST /user/customfields/{customFieldId}/contexts/{contextId}/options/{optionId}/childoptions`
 * `PUT  /user/customfields/{customFieldId}/contexts/{contextId}/options/{optionId}/childoptions/{childOptionId}`

HTTP 400 Response on Duplicate - **Before**

```
{
   "message":"validation errors",
   "statusCode":400,
   "subCode":400000,
   "errors":[
     {
       "name":"optionvalue",
       "message":"This option value does already exist. Option values need to be unique."
     }
   ]
}
```

HTTP 400 Response on Duplicate - **Now**

```
{
   "message":"validation errors",
   "statusCode":400,
   "subCode":400000,
   "errors":[
     {
         "name":"optionvalue",
         "message":"This option value does already exist. Option values need to be unique."
     },
     {
         "name":"existingOptionId",
         "message":"The id of the existing option with the same value.", 
         "value": 1234
     },
   ]
}
```

### Example

Let's assume you have these existing options

```
[
    {
        "optionvalue": "foo",
        "id": 123,
        "sequence": 1,
        "disabled": false
    },
    {
        "optionvalue": "bar",
        "id": 456,
        "sequence": 2,
        "disabled": false
    }
]
```

And you send an POST Request to create a new option

```
{
    "optionvalue": "FOO"
}
```

You will receive this HTTP 400 Validation Error Response

```
{
   "message":"validation errors",
   "statusCode":400,
   "subCode":400000,
   "errors":[
     {
         "name":"optionvalue",
         "message":"This option value does already exist. Option values need to be unique."
     },
     {
         "name":"existingOptionId",
         "message":"The id of the existing option with the same value.", 
         "value": 123
     },
   ]
}
```

**Comment by EmillkaakillmE** [comment]
That's great! You made a nice job!
